repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [
            --max-line-length=80,
            '--select=C,E,F,W,B,B950',
            '--ignore=E203,E501,W503',
        ]
        additional_dependencies: [
            'flake8-bugbear',
        ]
        exclude: '^.*/__init__.py$'
