from .tenant import TenantSchema
from .property import PropertySchema
from .lease import LeaseSchema
from .property_assignment import PropertyAssignSchema
from .user import *
from .staff_tenants import StaffTenantSchema
from .ticket import TicketSchema
from .notes import NotesSchema
from .emergency_contact import EmergencyContactSchema
from .contact_number import ContactNumberSchema
