name: CI Tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development


env:
  POSTGRES_HOST_AUTH_METHOD: trust
  PGUSER: postgres
  PGHOST: localhost
  SECRET_KEY: dwellingly
  TEST_DATABASE_URL: postgresql://localhost/dwellingly_test
  FLASK_ENV: testing

jobs:
  pytest:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install --user pipenv

      - name: Install dependecies
        run: pipenv run dev-install

      - name: Create db
        run: createdb dwellingly_test

      - name: Test
        run: |
          pipenv run pytest
          pipenv run pre-commit run --all-file
